repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: python -m ruff check . --no-cache
        language: system
        pass_filenames: false
      - id: ruff-format-check
        name: ruff format check
        entry: python -m ruff format . --check
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: python -m pytest
        language: system
        pass_filenames: false
